apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-uat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/swagat-devops/gitops-application-repo.git
    targetRevision: dev
    path: ./declarative/app-of-app/uat/
  destination:
    server: https://kubernetes.default.svc
    namespace: kubernetes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
